# PR size labeling configuration

size/XS:
  - changed-files: 0-9

size/S:
  - changed-files: 10-29

size/M:
  - changed-files: 30-99

size/L:
  - changed-files: 100-499

size/XL:
  - changed-files: 500-999

size/XXL:
  - changed-files: 1000+

