# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 60

# Number of days of inactivity before a stale Issue or Pull Request is closed
daysUntilClose: 14

# Issues or Pull Requests with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - critical
  - enhancement
  - good first issue
  - help wanted
  - roadmap
  - under consideration

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: false

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: true

# Set to true to ignore issues with an assignee (defaults to false)
exemptAssignees: false

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs within
  the next 14 days. Thank you for your contributions to MuseStat!
  
  If you believe this issue is still relevant, please:
  - Comment on this issue
  - Remove the 'stale' label
  - Provide any additional information or updates

# Comment to post when removing the stale label
unmarkComment: >
  This issue is no longer marked as stale. Thank you for keeping it active!

# Comment to post when closing a stale Issue or Pull Request
closeComment: >
  This issue has been automatically closed due to inactivity.
  
  If you still need help with this issue:
  - You can reopen it by commenting
  - Create a new issue referencing this one
  - Ask in [Discussions](https://github.com/Tfc538/MuseStat/discussions)
  
  Thank you for your interest in MuseStat!

# Limit the number of actions per hour
limitPerRun: 30

# Limit to only `issues` or `pulls`
# only: issues

# Optionally, specify configuration settings that are specific to just 'issues' or 'pulls':
pulls:
  daysUntilStale: 30
  daysUntilClose: 7
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs within
    the next 7 days.
    
    If you are still working on this PR:
    - Comment on this PR
    - Push new commits
    - Remove the 'stale' label
    
    Thank you for your contribution!

issues:
  daysUntilStale: 60
  daysUntilClose: 14

