name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  pr-title-check:
    name: Check PR Title
    runs-on: ubuntu-latest
    
    steps:
    - name: Check PR title format
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
        requireScope: false

  pr-size-check:
    name: Check PR Size
    runs-on: ubuntu-latest
    
    steps:
    - name: Check PR size
      uses: actions/labeler@v6
      with:
        configuration-path: .github/pr-labeler.yml
        sync-labels: true

  changelog-check:
    name: Check CHANGELOG Updated
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.pull_request.labels.*.name, 'documentation') &&
      !contains(github.event.pull_request.labels.*.name, 'dependencies')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Check if CHANGELOG.md is modified
      run: |
        if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -q "CHANGELOG.md"; then
          echo "✅ CHANGELOG.md has been updated"
          exit 0
        else
          echo "⚠️ CHANGELOG.md has not been updated"
          echo "Please add an entry to CHANGELOG.md describing your changes"
          exit 1
        fi
      continue-on-error: true

  pr-labels:
    name: Label PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Auto-label PR
      uses: actions/labeler@v6
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/labeler.yml
        sync-labels: true

  pr-comment:
    name: Welcome Comment
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    
    steps:
    - name: Comment on first-time PR
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: |
          👋 Thank you for submitting your first pull request to MuseStat!
          
          A maintainer will review your PR soon. In the meantime, please ensure:
          - ✅ You've read the [Contributing Guidelines](../CONTRIBUTING.md)
          - ✅ All tests pass
          - ✅ You've updated documentation if needed
          - ✅ You've added an entry to CHANGELOG.md
          
          We appreciate your contribution! 🎉

  docs-check:
    name: Check Documentation
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'documentation')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Check for broken links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/markdown-link-check-config.json'
        folder-path: 'docs/'
      continue-on-error: true

