name: Build and Release

on:
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Build Windows executable
        run: |
          pyinstaller --onefile --name musestat --console main.py
      
      - name: Upload Windows executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/musestat.exe
          asset_name: musestat-windows-x64.exe
          asset_content_type: application/octet-stream

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Build Linux executable
        run: |
          pyinstaller --onefile --name musestat --console main.py
      
      - name: Upload Linux executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/musestat
          asset_name: musestat-linux-x64
          asset_content_type: application/octet-stream

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Build macOS executable
        run: |
          pyinstaller --onefile --name musestat --console main.py
      
      - name: Upload macOS executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/musestat
          asset_name: musestat-macos-x64
          asset_content_type: application/octet-stream

  update-version:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-macos]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update version.json
        run: |
          VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')
          echo "{" > version.json
          echo "  \"version\": \"$VERSION\"," >> version.json
          echo "  \"release_date\": \"$(date +%Y-%m-%d)\"," >> version.json
          echo "  \"release_notes_url\": \"https://github.com/Tfc538/MuseStat/releases/tag/${{ github.event.release.tag_name }}\"" >> version.json
          echo "}" >> version.json
      
      - name: Commit version update
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add version.json
          git commit -m "Update version.json for release ${{ github.event.release.tag_name }}" || echo "No changes to commit"
          git push || echo "Nothing to push"

